; PlatformIO Project Configuration File

[env:main1] ; Emisor ESP32
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = 
    CAN-Library/MART_CAN/lib
monitor_speed = 115200
build_src_filter = +<*.*> -<main2.cpp> 
build_flags = ${env.build_flags}
monitor_filters = esp32_exception_decoder
upload_port = COM6
monitor_port = COM6

[env:main2] ; Receptor ESP32
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = 
    CAN-Library/MART_CAN/lib
monitor_speed = 115200
build_src_filter = +<*.*> -<main1.cpp> 
build_flags = ${env.build_flags}
monitor_filters = esp32_exception_decoder

[env:nucleo_g474re_main1] ; Emisor STM32
platform = ststm32
board = nucleo_g474re
framework = arduino
lib_extra_dirs = 
    CAN-Library/MART_CAN/lib
monitor_speed = 115200
upload_protocol = stlink
build_src_filter = +<*.*> -<main2.cpp> 
build_flags = -D HAL_FDCAN_MODULE_ENABLED

[env:nucleo_g474re_main2] ; Receptor STM32
platform = ststm32
board = nucleo_g474re
framework = arduino
lib_extra_dirs = 
    CAN-Library/MART_CAN/lib
monitor_speed = 115200
build_src_filter = +<*.*> -<main1.cpp> 
build_flags = -D HAL_FDCAN_MODULE_ENABLED
upload_protocol = stlink
