; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
build_flags = -std=c++11
build_unflags = -std=gnu++17
monitor_speed = 115200
lib_deps = 
    autowp/autowp-mcp2515@^1.0.3
    
   # https://github.com/mike-matera/ArduinoSTL.git

[env:esp32]
platform = espressif32
board = esp32dev
build_src_filter = +<main11.cpp> 
build_flags = ${env.build_flags}
                -D ESP32
upload_port = /dev/ttyUSB0

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
build_src_filter = +<main.cpp>
build_flags = ${env.build_flags}
                -D ESP32
upload_port = /dev/ttyUSB1
lib_deps =
    ${env.lib_deps}

[env:arduinonano]
platform = atmelavr
board = nanoatmega328new 
build_src_filter = +<main.cpp>
build_flags = ${env.build_flags}
                -D ARDUINO_MICRO
lib_deps =
    ${env.lib_deps}
    https://github.com/mike-matera/ArduinoSTL.git
upload_port = /dev/ttyUSB0

[env:arduinomega]
platform = atmelavr
board = megaatmega2560
build_src_filter = +<main11.cpp>
build_flags = ${env.build_flags}
                -D ARDUINO_MEGA
upload_port = /dev/ttyUSB0
lib_deps =
    ${env.lib_deps}
    https://github.com/mike-matera/ArduinoSTL.git

[platformio]
description = MART custom library

#Para cargar los dos programas a las dos ESP de forma automática:
#1. Pulsar en el icono de platformio en la barra de la izquierda / Quick Access / Miscellaneous / Pulsar en PlatformIO Core
#2. Escribir en la terminal lo siguiente, cambiando los puertos (dev/ttyUSB0) por los vuestros (COM...): 
# pio run -e main1 -t upload --upload-port /dev/ttyUSB0 && pio run -e main2 -t upload --upload-port /dev/ttyUSB1

#Para cargarlos de manera individual, en teoría cuando cambiáis de entorno se debería de cambiar el puerto serial de forma 
# automática (el que hayáis puesto en el parámetro "upload_port"), si no debéis de hacerlo de forma manual o ejecutando uno de los dos comandos de los de arriba en la terminal

