; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
monitor_speed = 115200

[env:main]
build_src_filter = +<*.*> -<main1.cpp> -<main2.cpp>
build_flags = ${env.build_flags}
upload_port=COM5

[env:main1]
build_src_filter = +<*.*> -<main.cpp> -<main2.cpp>
build_flags = ${env.build_flags}
upload_port=COM5

[env:main2]
build_src_filter = +<*.*> -<main.cpp> -<main1.cpp>
build_flags = ${env.build_flags}
upload_port=COM6

[platformio]
description = MART custom library

#Para cargar los dos programas a las dos ESP de forma automática:
#1. Pulsar en el icono de platformio en la barra de la izquierda / Quick Access / Miscellaneous / Pulsar en PlatformIO Core
#2. Escribir en la terminal lo siguiente, cambiando los puertos (dev/ttyUSB0) por los vuestros (COM...): 
# pio run -e main1 -t upload --upload-port /dev/ttyUSB0 && pio run -e main2 -t upload --upload-port /dev/ttyUSB1

#Para cargarlos de manera individual, en teoría cuando cambiáis de entorno se debería de cambiar el puerto serial de forma 
# automática (el que hayáis puesto en el parámetro "upload_port"), si no debéis de hacerlo de forma manual o ejecutando uno de los dos comandos de los de arriba en la terminal

